### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by CV1523** [gokulapap/freedemy#1]
pip3 install -r requirements.txt
Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.25.1)
**ERROR: Could not find a version that satisfies the requirement googlesearch
ERROR: No matching distribution found for googlesearch**
 getting error bro

**Comment by gokulapap** [comment]
Hey thanks for pointing this issue , that is a small mistake
pip3 install google
Install this module to install google search
I will commit this change !
