### ISSUE TITLE
Now able to gen codes

### ISSUE THREAD

**Issue by harshitkamboj** [gokulapap/freedemy#3]
sh: figlet: not found
sh: lolcat: not found                                                
- BY GOKUL -                                                                     ==============================================================================================================                                                                                                                                                                                              Traceback (most recent call last):                  File "/data/data/com.termux/files/home/freedemy/free-courses.py", line 34, in <module>
    soup = BeautifulSoup(content, 'lxml')           File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/bs4/__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by gokulapap** [comment]
I hope youre using Linux
Install this and try again

apt install figlet
apt install lolcat

pip3 install lxml

This may fix your error

**Comment by harshitkamboj** [comment]
I am using termux 🤧
